export const RouteNames = {
  SIGN_IN: '/auth/sign-in',
  SIGN_UP: '/auth/sign-up',
  AUTH: '/auth',
  PASSWORD_RECOVERY: '/auth/password-recovery',
  CREATE_NEW_PASSWORD: '/auth/create-new-password',
  NEW_PASSWORD: '/auth/new-password',
  PROFILE: '/profile',
  PROFILE_SETTINGS: '/profile/settings',
  PRIVACY_POLICY: '/auth/privacy-policy',
  TERMS_OF_USE: '/auth/terms-of-use',
  FAVORITES: '/favorites',
  MESSAGE: '/message',
  HOME: '/home',
  SEARCH: '/search',
  STATISTICS: '/statistics',
  POSTS: '/posts',
} as const
