export { getIsAuth } from '@/shared/hoc/model/selectors/getIsAuth/getIsAuth'
export { getUserEmail } from '@/shared/hoc/model/selectors/getUserEmail/getUserEmail'
export { getUserId } from '@/shared/hoc/model/selectors/getUserId/getUserId'
export { getUsername } from '@/shared/hoc/model/selectors/getUsername/getUsername'
export { authMeReducer, setAuthMeData } from '@/shared/hoc/model/slice/authMeSlice'
export type { AuthMeSchema } from '@/shared/hoc/model/types/AuthMeSchema'
export { useGetMeQuery } from '@/shared/hoc/service/authProvider'
export { AuthProvider } from '@/shared/hoc/ui/AuthProvider'
