export const RouteNames = {
  AUTH: '/auth',
  CREATE_NEW_PASSWORD: '/auth/create-new-password',
  CREATE_POST: '/create-post',
  DEVICES: '/profile/settings/devices',
  EMAIL_VERIFICATION: '/auth/email-verification',
  FAVORITES: '/favorites',
  HOME: '/home',
  INVALID_LINK_VERIFICATION: '/auth/invalid-link-verification',
  LOGOUT: '/logout',
  MESSAGE: '/message',
  NEW_PASSWORD: '/auth/new-password',
  PASSWORD_RECOVERY: '/auth/password-recovery',
  POST: '/post',
  POSTS: '/posts',
  PRIVACY_POLICY: '/auth/privacy-policy',
  PROFILE: '/profile',
  PROFILE_SETTINGS: '/profile/settings',
  PUBLIC_PAGE: '/',
  SEARCH: '/search',
  SIGN_IN: '/auth/sign-in',
  SIGN_UP: '/auth/sign-up',
  STATISTICS: '/statistics',
  TERMS_OF_USE: '/auth/terms-of-use',
} as const
